### ISSUE TITLE
[Request] Merge Angel with Sorcerer

### ISSUE THREAD

**Issue by LIRV7** [vikigenius/SpellbookMerge#13]
Thank you for this awesome mod!!

It would be great if you could add this option in a future update.

Thanks in advance :)

**Comment by vikigenius** [comment]
Yeah, I won't really be doing this. I prefer to keep my mod as thematic as possible, and Owlcat have decided to merge Angel with divine casters only, and I would keep it that way, especially since Angel is an existing path and would have to be patched.

On the other hand Sorcerer is a full caster, so you should have no problem using the ToyBox merge, it will work perfectly fine.
