### ISSUE TITLE
Any plans, or possibility of allowing lich to merge with divine?

### ISSUE THREAD

**Issue by bulldogc** [vikigenius/SpellbookMerge#22]
I'd really like to be able to merge my oracle or cleric to lich, any chance of adding this in?

**Comment by vikigenius** [comment]
Nope, I no longer play the game so I won't be adding any new features since I have no way to test them. I will still consider fixing any game breaking bugs due to future game updates since my mod introduces a save dependency.

But the codebase is in pretty good shape, so if someone creates a PR after testing the changes on their own machine, I would welcome it.
